### ISSUE TITLE
Dark Google Collection interferes with document colors

### ISSUE THREAD

**Issue by PhantomFury22** [Jordy3D/Jordy3D.github.io#1]
The change that darkens Google Docs also alters the color of the document to where what was otherwise legible without the Style proved to be illegible with it enabled. This would cause issues when sharing documents between people with and without the style installed. It should also be noted that this also changes the color of the tables.

Without the Style:
![image](https://user-images.githubusercontent.com/74842579/99891133-d2f9dd00-2c23-11eb-8e00-dd0ef500a3fa.png)
With the Style:
![image](https://user-images.githubusercontent.com/74842579/99891146-f3c23280-2c23-11eb-8c3f-8f64365ff690.png)

Without the Style:
![image](https://user-images.githubusercontent.com/74842579/99891160-266c2b00-2c24-11eb-9037-cd31001e6da8.png)
With the Style:
![image](https://user-images.githubusercontent.com/74842579/99891164-34ba4700-2c24-11eb-8f6b-c661e1382cad.png)

Additional info:
This is done on Chrome

**Comment by Jordy3D** [comment]
Ah, the Google Docs colour changes are a little... fiddly for now. I've actually been fighting with those for a while. 
Because of how it all works, there's really three options for it going forward
- Keep it like this and do minor modifications to readability (which may work in one case but fail in others)
- Shift to my alternate colour scheme for the Docs which would make just the page dark (and black text white), but other elements would not be recoloured at all (most compatibility, at the cost of table elements, darkenened sections and the light not working on the Dark theme)
- Make no changes at all to the page itself, instead just darkening everything else around it

It's kinda a shame we gotta work in these limits, but until then if you want to maximise compatibility with non-style users (which will forever be the majority), you're gonna have to enable/disable the style to check it looks right before sending

**Comment by Jordy3D** [comment]
Here's some CSS that will override the current state (option 1 from the previous comment) for now. Add this to the bottom of the section marked "Applies to: docs.google.com".  

Option 2 - Cleaner dark, less compatibility 
```css
/* Alternate Dark Mode- Option 2 */
.docs-gm #docs-editor *[style*="background-color: rgb(255, 255, 255)"]
{
    background: #2e2e2f !important;
}

*[style*="000"]
{
  color: #ccc !important;
}

.kix-zoomdocumentplugin-outer, .kix-embeddedobject-view
{
  filter: invert(0) !important;
}
```

Option 3 - Disable Dark altogether for the page element
```css
/* Alternate Dark Mode- Option 3 */
.docs-gm #docs-editor *[style*="background-color: rgb(255, 255, 255)"]
{
    background: white;
}

.kix-zoomdocumentplugin-outer,
.kix-embeddedobject-view
{
  filter: invert(0) !important;
}
```
